IdanS
norbit8/MoodleBooster pull request #11
Opened 2021-05-08 10:28 UTC by idan2468

Added dark mode logo moodle and HUJI logos and a little clean up code

2021-05-08 11:55 UTC, norbit8 requested changes

2021-05-08 11:55 UTC, norbit8 commented on content_scripts/storageLoader.js
> +    hujiLogoImg.setAttribute("src","https://i.ibb.co/6mdGRfv/moodle-huji-logo-darkmode.png")
You can add the images to our `/images` folder, it will be safer because I don't know how long does "ibb" will save the images for.

2021-05-08 11:55 UTC, norbit8 commented on content_scripts/storageLoader.js
> +                removeDarkMode();
Nice 👍🏼

2021-05-22 08:37 UTC, yanirelfasy approved these changes

2021-05-22 08:40 UTC, merged